# Generated by Django 4.2.2 on 2023-11-08 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0013_course_course_weigth_course_eitaa_course_is_discount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoadMaps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='نام رودمپ')),
                ('small_description', models.CharField(max_length=150, verbose_name='توضیحات پیش نمایش')),
                ('image', models.ImageField(upload_to='', verbose_name='عکس ایکون رودمپ')),
            ],
            options={
                'verbose_name': 'رودمپ ',
                'verbose_name_plural': 'رودمپ ها',
            },
        ),
        migrations.CreateModel(
            name='RoadMapDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_number', models.IntegerField(verbose_name='شماره دوره ')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.course', verbose_name='دوره مورد نظر')),
                ('roadmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roadmap.roadmaps', verbose_name='رودمپ مورد نظر')),
            ],
            options={
                'verbose_name': 'دوره های  رودمپ',
                'verbose_name_plural': 'دوره های هر رودمپ',
            },
        ),
    ]
