# Generated by Django 4.2.2 on 2023-11-10 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadmaps',
            name='image',
            field=models.TextField(verbose_name='عکس ایکون رودمپ'),
        ),
    ]
