# Generated by Django 4.2.2 on 2023-11-10 08:49

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0002_alter_roadmaps_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadmaps',
            name='description',
            field=ckeditor.fields.RichTextField(default='به زودی اضافه می گردد...', verbose_name='توضیحات کامل درباره رودمپ'),
        ),
    ]
