# Generated by Django 4.2.2 on 2024-01-20 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0003_roadmaps_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadmaps',
            name='color',
            field=models.CharField(default='', max_length=50, verbose_name='رنگ رودمپ'),
        ),
    ]
