# Generated by Django 4.2.2 on 2024-01-21 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0004_roadmaps_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadmaps',
            name='cover_image',
            field=models.ImageField(null=True, upload_to='', verbose_name='عکس پیش نمایش رودمپ'),
        ),
        migrations.AddField(
            model_name='roadmaps',
            name='video_id',
            field=models.CharField(max_length=800, null=True, verbose_name='آی دی ویدئو'),
        ),
    ]
