# Generated by Django 4.2.2 on 2024-01-21 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0005_roadmaps_cover_image_roadmaps_video_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadmaps',
            name='voice_id',
            field=models.CharField(max_length=800, null=True, verbose_name='آی دی فایل صوتی '),
        ),
    ]
