# Generated by Django 4.2.2 on 2024-01-26 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0006_roadmaps_voice_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadmaps',
            name='discount_date',
            field=models.CharField(default='', help_text=' مثال:Dec 31, 2024 23:59:59', max_length=50, verbose_name='تاریخ تخفیف رودمپ'),
        ),
        migrations.AddField(
            model_name='roadmaps',
            name='is_discount',
            field=models.BooleanField(default=False, help_text='در صورت زدن این تیک تایمر تخفیف رودمپ فعال می شود', verbose_name='تایمر تخفیف رودمپ'),
        ),
    ]
