# Generated by Django 4.2.2 on 2024-07-07 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0007_roadmaps_discount_date_roadmaps_is_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadmaps',
            name='main_image',
            field=models.ImageField(null=True, upload_to='', verbose_name='عکس اصلی رودمپ'),
        ),
    ]
