# Generated by Django 4.2.2 on 2024-07-10 07:19

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0008_roadmaps_main_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='طرح سوال')),
                ('description', ckeditor.fields.RichTextField(default='به زودی اضافه می گردد...', verbose_name='توضیحات سوال')),
                ('roadmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='roadmap.roadmaps', verbose_name='رودمپ مورد نظر')),
            ],
        ),
    ]
