# Generated by Django 4.2.2 on 2024-07-10 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0009_topquestions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topquestions',
            name='name',
            field=models.CharField(max_length=255, verbose_name='طرح سوال'),
        ),
    ]
