# Generated by Django 4.2.2 on 2023-08-20 12:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0012_remove_course_faze_selling_price_and_more'),
        ('ATM', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Payment_data',
            new_name='Payment_Course_Data',
        ),
    ]
