# Generated by Django 4.2.2 on 2023-08-20 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ATM', '0002_rename_payment_data_payment_course_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment_Course_Data',
        ),
    ]
