# Generated by Django 4.2.2 on 2023-08-22 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_remove_course_faze_selling_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ATM', '0004_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment_Faze_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=50)),
                ('status', models.IntegerField()),
                ('RefId', models.CharField(max_length=50)),
                ('is_success', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('faze', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.course_faze')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
