# Generated by Django 4.2.2 on 2023-08-24 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ATM', '0005_payment_faze_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_faze_data',
            name='RefId',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='payment_faze_data',
            name='status',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
