# Generated by Django 4.2.2 on 2023-08-24 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ATM', '0007_alter_payment_course_data_refid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_faze_data',
            name='price',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
