# Generated by Django 4.2.2 on 2024-07-13 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ATM', '0009_consultationrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationrequest',
            name='authority',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
