# Generated by Django 4.2.2 on 2023-09-30 14:10

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='نام اسلاید')),
                ('image', models.ImageField(upload_to='', verbose_name='عکس اسلاید')),
                ('link', models.CharField(max_length=250, verbose_name='لینک پیوست شده به اسلاید')),
            ],
            options={
                'verbose_name': 'اسلایدر وبلاگ',
                'verbose_name_plural': 'اسلایدر وبلاگ',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('slug', models.SlugField(help_text='حتما باید با حروف انگلیسی باشه و بین حروف اسپیس نباشه این نکته خیلی مهمه', max_length=150, verbose_name='اسلاگ')),
                ('trending', models.BooleanField(default=False, verbose_name='پست برگزیده هفته')),
                ('body', models.TextField(verbose_name='پیشگفتار')),
                ('content', ckeditor.fields.RichTextField(verbose_name='محتوای اصلی')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ نوشتن')),
                ('image', models.ImageField(blank=True, default='default.jpg', upload_to='', verbose_name='عکس اصلی مقاله')),
            ],
            options={
                'verbose_name': 'پست های وبلاگ',
                'verbose_name_plural': 'پست های وبلاگ',
            },
        ),
    ]
