# Generated by Django 4.2.2 on 2024-05-15 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_meta_description_post_meta_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='meta_description',
            field=models.TextField(blank=True, default='data', max_length=600, null=True, verbose_name='متا توضیحات'),
        ),
        migrations.AlterField(
            model_name='post',
            name='meta_title',
            field=models.CharField(blank=True, default='data', help_text='تمام فیلد هایی که با متا نام گذاری شده اند برای مباحس سئو استفاده می شوند با دقت پر کنید', max_length=150, null=True, verbose_name='متا تایتل'),
        ),
    ]
