# Generated by Django 4.2.2 on 2024-07-01 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_meta_description_alter_post_meta_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_podcast',
            field=models.BooleanField(default=False, verbose_name='پادکست بودن'),
        ),
    ]
