# Generated by Django 4.2.2 on 2024-07-03 06:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0005_post_is_podcast'),
    ]

    operations = [
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('slug', models.SlugField(help_text='حتما باید با حروف انگلیسی باشه و بین حروف اسپیس نباشه این نکته خیلی مهمه', max_length=150, verbose_name='اسلاگ')),
                ('length', models.TimeField(verbose_name='تایم پادکست')),
                ('body', models.TextField(verbose_name='پیشگفتار')),
                ('audio_link', models.URLField(max_length=500)),
                ('image', models.ImageField(blank=True, default='default.jpg', upload_to='', verbose_name='عکس اصلی مقاله')),
                ('meta_title', models.CharField(blank=True, default='data', help_text='تمام فیلد هایی که با متا نام گذاری شده اند برای مباحس سئو استفاده می شوند با دقت پر کنید', max_length=150, null=True, verbose_name='متا تایتل')),
                ('meta_description', models.TextField(blank=True, default='data', max_length=600, null=True, verbose_name='متا توضیحات')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ نوشتن')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
                ('related_post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.post', verbose_name='پست مرتبط')),
            ],
            options={
                'verbose_name': 'پادکست های وبلاگ',
                'verbose_name_plural': 'پادکست های وبلاگ',
            },
        ),
    ]
