# Generated by Django 4.2.2 on 2024-07-13 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_course_fake_student_course_is_fake_student'),
        ('blog', '0006_podcast'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='course_related',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.course', verbose_name='دوره مرتبت'),
        ),
    ]
