"""
Django settings for academycodna project.

Generated by 'django-admin startproject' using Django 4.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG')

DEPLOY = os.getenv('DEPLOY')

ALLOWED_HOSTS = []

AUTH_USER_MODEL = 'users.CustomUser'

# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # django two factor authentication
    'django_otp',
    'django_otp.plugins.otp_totp',

    'home',
    'blog',
    'cart',
    'users',
    # config ckeditor
    'ckeditor',

    'ATM',
    'dashboard',
    'editor',
    'roadmap',
    'MembersDietail',
    #     single user logs in

    'single_session',

    #     sso
    'django_sso.sso_gateway',
]
# sso configuration
# SSO settings section in the gateway side are optional
SSO = {
    # Timeout for the communication with subordinated services. (OPTIONAL)
    # This timeout is defined in seconds with a default value of 0.1s
    # (100ms) per registered service.
    'SUBORDINATE_COMMUNICATION_TIMEOUT': 0.1,

    # Additional fields. (OPTIONAL). For more details look to part
    # named as "Send additional data to subordinated services"
    # 'ADDITIONAL_FIELDS': ('additiona_fields', 'from_user_model', 'and_related_models'),
}

# Affects to the "welcome" url (after successful authentication) when
# user logged in but don't have url to redirect. Optional.
# Compatible logic with Django.
# LOGIN_REDIRECT_URL = '/default/url/'
#  single user logs in

SESSION_ENGINE = 'django.contrib.sessions.backends.db'
LOGOUT_DAYS = 3
AUTO_LOGOUT = {'SESSION_TIME': LOGOUT_DAYS * 24 * 60 * 60}

# zarinpal config

MERCHANT = "fb923a1f-bd72-493c-9545-088ff34c039d"

SANDBOX = os.getenv('SANDBOX')

CODENA_URL = os.getenv('CODENA_URL')

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',

    # django two factor authentication
    'django_otp.middleware.OTPMiddleware',

    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    #     single user logs in
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django_auto_logout.middleware.auto_logout',

]

ROOT_URLCONF = 'academycodna.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # search box context processors
                'utils.context_processors.search_context'
            ],
        },
    },
]

WSGI_APPLICATION = 'academycodna.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

if DEPLOY != True:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',

            # Just for development mode
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
        }
    }

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/


LANGUAGE_CODE = 'fa-ir'

TIME_ZONE = 'Asia/Tehran'

USE_I18N = True

USE_TZ = True

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

STATIC_URL = 'static/'

MEDIA_URL = 'media/'

MEDIA_ROOT = BASE_DIR / 'media'

STATICFILES_DIRS = [
    BASE_DIR / 'static'
]
# comfig ckeditor upload files
CKEDITOR_UPLOAD_PATH = '/upload'

# حداکثر اندازه فایل بر حسب بایت (در این مثال 10 مگابایت)
FILES_UPLOAD_MAX_SIZE = 10 * 1024 * 1024  # 10 MB

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.c1.liara.email'
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = 'clever_colden_1787qd'
EMAIL_HOST_PASSWORD = 'fb2b6db5-cd1c-4945-9bd9-5891968091ab'

# celery configuration
CELERY_BROKER_URL = 'redis://localhost:6379'
# CELERY_RESULT_BACKEND = 'redis://:oHGucrmQwtEv69FgqjzyK2Fz@logan.liara.cloud:34570/0'
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Asia/Tehran'
