# Generated by Django 4.2.2 on 2023-07-15 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course_Faze',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('original_price', models.IntegerField()),
                ('selling_price', models.IntegerField()),
                ('is_free', models.BooleanField(default=False, help_text='اگر تیک را بزنید فاز به صورت رایگان ارزه می شود')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.course')),
            ],
        ),
    ]
