# Generated by Django 4.2.2 on 2023-07-15 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_course_faze'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course_Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=150)),
                ('video', models.FileField(null=True, upload_to='videos/', verbose_name='ویدیو')),
                ('is_free', models.BooleanField(default=False, help_text='اگر تیک را بزنید قسمت به صورت رایگان نمایش داده می شود')),
                ('course_faze', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.course_faze')),
            ],
        ),
    ]
