# Generated by Django 4.2.2 on 2023-07-15 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_course_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_section',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.course'),
        ),
    ]
