# Generated by Django 4.2.2 on 2023-07-15 09:27

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0004_course_section_course'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'دوره', 'verbose_name_plural': 'دوره ها'},
        ),
        migrations.AlterModelOptions(
            name='course_faze',
            options={'verbose_name': 'فاز های دوره ها', 'verbose_name_plural': 'فاز های دوره ها'},
        ),
        migrations.AlterModelOptions(
            name='course_section',
            options={'verbose_name': 'قسمت ها', 'verbose_name_plural': 'قسمت های هر فاز'},
        ),
        migrations.AlterModelOptions(
            name='discount',
            options={'verbose_name': 'سیستم کد تخفیف', 'verbose_name_plural': 'سیستم کد تخفیف'},
        ),
        migrations.AlterModelOptions(
            name='mainslider',
            options={'verbose_name': 'اسلاید ها', 'verbose_name_plural': 'اسلایدر'},
        ),
        migrations.RemoveField(
            model_name='course_section',
            name='course',
        ),
        migrations.AlterField(
            model_name='course',
            name='course_image',
            field=models.ImageField(upload_to='', verbose_name='عکس پیش نمایش دوره'),
        ),
        migrations.AlterField(
            model_name='course',
            name='creat_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ اضافه کردن دوره'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='توضیحات کامل دوره'),
        ),
        migrations.AlterField(
            model_name='course',
            name='discount_code',
            field=models.ForeignKey(help_text='برای استفاده از کد تخفیف اول باید یک کد تخفیف بسازید و بعد اینجا انتخابش کنید', null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.discount', verbose_name='درصد تخفیف دوره'),
        ),
        migrations.AlterField(
            model_name='course',
            name='meta_description',
            field=models.TextField(max_length=600, verbose_name='متا توضیحات'),
        ),
        migrations.AlterField(
            model_name='course',
            name='meta_keywords',
            field=models.CharField(max_length=150, verbose_name='متا کلمات کیلیدی'),
        ),
        migrations.AlterField(
            model_name='course',
            name='meta_title',
            field=models.CharField(help_text='تمام فیلد هایی که با متا نام گذاری شده اند برای مباحس سئو استفاده می شوند با دقت پر کنید', max_length=150, verbose_name='متا تایتل'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=150, verbose_name='نام دوره'),
        ),
        migrations.AlterField(
            model_name='course',
            name='original_price',
            field=models.IntegerField(verbose_name='قیمت اصلی دوره'),
        ),
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.CharField(help_text='حتما باید با حروف انگلیسی باشه و بین حروف اسپیس نباشه این نکته خیلی مهمه', max_length=150, verbose_name='اسلاگ'),
        ),
        migrations.AlterField(
            model_name='course',
            name='small_description',
            field=models.CharField(max_length=800, verbose_name='توضیحات پیش نمایش'),
        ),
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.BooleanField(default=False, help_text='در صورت زدن این تیک توره به سورت رایگان نمایش داده می شود', verbose_name='رایگان بودن دوره'),
        ),
        migrations.AlterField(
            model_name='course',
            name='tag',
            field=models.CharField(max_length=150, verbose_name='تگ های مرتبط به دوره'),
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='مدرس'),
        ),
        migrations.AlterField(
            model_name='course',
            name='trending',
            field=models.BooleanField(default=False, help_text='در صورت زدن این تیک دوره در قسمت پیشنهاد های کدنا نمایش داده می شود', verbose_name='پیشنهاد های کدنا'),
        ),
        migrations.AlterField(
            model_name='course_faze',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.course', verbose_name='دوره مورد نظر'),
        ),
        migrations.AlterField(
            model_name='course_faze',
            name='is_free',
            field=models.BooleanField(default=False, help_text='اگر تیک را بزنید فاز به صورت رایگان ارزه می شود', verbose_name='رایگان بودن'),
        ),
        migrations.AlterField(
            model_name='course_faze',
            name='name',
            field=models.CharField(max_length=150, verbose_name='نام فاز'),
        ),
        migrations.AlterField(
            model_name='course_faze',
            name='original_price',
            field=models.IntegerField(verbose_name='قیمت اصلی فاز '),
        ),
        migrations.AlterField(
            model_name='course_faze',
            name='selling_price',
            field=models.IntegerField(verbose_name='قیمت فروش فاز با تخفیف'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='code',
            field=models.CharField(max_length=150, verbose_name='کد تخفیف'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='percent',
            field=models.IntegerField(verbose_name='درصد تخفیف'),
        ),
        migrations.AlterField(
            model_name='mainslider',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='عکس اسلاید'),
        ),
        migrations.AlterField(
            model_name='mainslider',
            name='link',
            field=models.CharField(max_length=250, verbose_name='لینک پیوست شده به اسلاید'),
        ),
        migrations.AlterField(
            model_name='mainslider',
            name='name',
            field=models.CharField(max_length=150, verbose_name='نام اسلاید'),
        ),
    ]
