# Generated by Django 4.2.2 on 2023-07-15 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_course_options_alter_course_faze_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course_section',
            options={'verbose_name': 'قسمت ها', 'verbose_name_plural': 'قسمت های هر فصل'},
        ),
        migrations.RemoveField(
            model_name='course_section',
            name='course_faze',
        ),
        migrations.AlterField(
            model_name='course_section',
            name='section_name',
            field=models.CharField(max_length=150, verbose_name='نام قسمت'),
        ),
        migrations.CreateModel(
            name='Course_Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='نام فصل')),
                ('is_free', models.BooleanField(default=False, help_text='اگر تیک را بزنید فصل به صورت رایگان ارزه می شود', verbose_name='رایگان بودن')),
                ('course_faze', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.course_faze', verbose_name='فاز مورد نظر')),
            ],
            options={
                'verbose_name': 'فصل ها',
                'verbose_name_plural': 'فصل های هر فاز',
            },
        ),
        migrations.AddField(
            model_name='course_section',
            name='course_season',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.course_season', verbose_name='فصل مورد نظر'),
        ),
    ]
