# Generated by Django 4.2.2 on 2023-07-15 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_course_section_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course_Seasons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='نام فصل')),
                ('is_free', models.BooleanField(default=False, help_text='اگر تیک را بزنید فصل به صورت رایگان ارزه می شود', verbose_name='رایگان بودن')),
                ('course_faze', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.course_faze', verbose_name='فاز مورد نظر')),
            ],
            options={
                'verbose_name': 'فصل ها',
                'verbose_name_plural': 'فصل های هر فاز',
            },
        ),
        migrations.CreateModel(
            name='Course_Sections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=150, verbose_name='نام قسمت')),
                ('video', models.FileField(null=True, upload_to='videos/', verbose_name='ویدیو')),
                ('is_free', models.BooleanField(default=False, help_text='اگر تیک را بزنید قسمت به صورت رایگان نمایش داده می شود')),
                ('course_season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.course_seasons', verbose_name='فصل مورد نظر')),
            ],
            options={
                'verbose_name': 'قسمت ها',
                'verbose_name_plural': 'قسمت های هر فصل',
            },
        ),
        migrations.RemoveField(
            model_name='course_section',
            name='course_season',
        ),
        migrations.DeleteModel(
            name='Course_Season',
        ),
        migrations.DeleteModel(
            name='Course_Section',
        ),
    ]
