# Generated by Django 4.2.2 on 2023-07-17 05:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0007_course_seasons_course_sections_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_sections',
            name='is_free',
            field=models.BooleanField(default=False, help_text='اگر تیک را بزنید قسمت به صورت رایگان نمایش داده می شود', verbose_name='رایگان بودن'),
        ),
        migrations.CreateModel(
            name='Faze_Selled',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creat_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ اضافه کردن فاز')),
                ('buyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='خریدار')),
                ('course_faze', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.course_faze', verbose_name='فاز مورد نظر')),
            ],
        ),
        migrations.CreateModel(
            name='Course_Selled',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creat_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ اضافه کردن دوره')),
                ('buyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='خریدار')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.course', verbose_name='دوره مورد نظر')),
            ],
        ),
    ]
