# Generated by Django 4.2.2 on 2023-07-17 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_course_sections_is_free_faze_selled_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course_selled',
            options={'verbose_name': 'خرید دوره', 'verbose_name_plural': 'سیستم خرید دوره'},
        ),
        migrations.AlterModelOptions(
            name='faze_selled',
            options={'verbose_name': 'خرید فاز', 'verbose_name_plural': 'سیستم خرید فاز'},
        ),
    ]
