# Generated by Django 4.2.2 on 2023-07-19 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_course_selled_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='temporary_discount_code',
            field=models.CharField(max_length=150, null=True, verbose_name='کد تخفیف موقت'),
        ),
        migrations.AddField(
            model_name='course_faze',
            name='temporary_discount_code',
            field=models.CharField(max_length=150, null=True, verbose_name='کد تخفیف موقت'),
        ),
    ]
