# Generated by Django 4.2.2 on 2023-08-03 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_course_temporary_discount_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course_sections',
            name='video',
        ),
        migrations.AddField(
            model_name='course_sections',
            name='video_id',
            field=models.CharField(max_length=800, null=True, verbose_name='آی دی ویدئو'),
        ),
    ]
