# Generated by Django 4.2.2 on 2023-08-10 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_course_sections_video_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course_faze',
            name='selling_price',
        ),
        migrations.AddField(
            model_name='course_faze',
            name='discount_code',
            field=models.ForeignKey(help_text='برای استفاده از کد تخفیف اول باید یک کد تخفیف بسازید و بعد اینجا انتخابش کنید', null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.discount', verbose_name='درصد تخفیف دوره'),
        ),
    ]
