# Generated by Django 4.2.2 on 2023-09-30 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_remove_course_faze_selling_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_weigth',
            field=models.CharField(default='0 ساعت', max_length=50, verbose_name='زمان حدودی تمام قسمت های دوره'),
        ),
        migrations.AddField(
            model_name='course',
            name='eitaa',
            field=models.CharField(max_length=250, null=True, verbose_name='لینک کانال ایتای دوره'),
        ),
        migrations.AddField(
            model_name='course',
            name='is_discount',
            field=models.BooleanField(default=False, help_text='در صورت زدن این تیک تخیفیف ها روی این دوره اعمال می شود', verbose_name='اعمال تخفیف دوره'),
        ),
        migrations.AddField(
            model_name='course',
            name='support',
            field=models.CharField(default='پشتیبانی دائمی', max_length=150, verbose_name='درباره پشتیبانی دوره'),
        ),
        migrations.AddField(
            model_name='course_faze',
            name='is_discount',
            field=models.BooleanField(default=False, help_text='در صورت زدن این تیک تخیفیف ها روی این فاز اعمال می شود', verbose_name='اعمال تخفیف فاز'),
        ),
    ]
