# Generated by Django 4.2.2 on 2023-12-30 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_course_course_weigth_course_eitaa_course_is_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_sections',
            name='is_google_drive',
            field=models.BooleanField(default=False, help_text='اگر تیک را بزنید تنظیمات پلی از گوگل درایو لحاظ می شود', verbose_name='اپلود از گوگل درایو'),
        ),
    ]
