# Generated by Django 4.2.2 on 2024-01-29 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_course_sections_is_google_drive'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_price_show',
            field=models.BooleanField(default=False, help_text='در صورت زدن این تیک قیمت نمایشی این دوره به صورت خط خورده نمایش داده می شود', verbose_name='نمایش قیمت نمایشی'),
        ),
        migrations.AddField(
            model_name='course',
            name='show_price',
            field=models.IntegerField(null=True, verbose_name='قیمت نمایشی دوره'),
        ),
    ]
