# Generated by Django 4.2.2 on 2024-03-07 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_course_is_price_show_course_show_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_sections',
            name='download_access',
            field=models.BooleanField(default=True, help_text='اگر تیک را بزنید قسمت قابل دانلود خواهد بود', verbose_name='قابلیت دانلود'),
        ),
    ]
