# Generated by Django 4.2.2 on 2024-03-16 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_course_sections_download_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='discount_date',
            field=models.CharField(default='', help_text=' مثال:Dec 31, 2024 23:59:59', max_length=50, verbose_name='تاریخ تخفیف رودمپ'),
        ),
        migrations.AddField(
            model_name='course',
            name='is_discount_timer',
            field=models.BooleanField(default=False, help_text='در صورت زدن این تیک تایمر تخفیف رودمپ فعال می شود', verbose_name='تایمر تخفیف رودمپ'),
        ),
    ]
