# Generated by Django 4.2.2 on 2024-06-26 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_tickets_remove_ticket_course_remove_ticket_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket_Uploader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_url', models.URLField(max_length=255)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_uploader', to='home.tickets')),
            ],
        ),
    ]
