# Generated by Django 4.2.2 on 2024-07-02 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_ticket_uploader'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'سیستم سرچ',
                'verbose_name_plural': 'افزودن فیلد های سرچ',
            },
        ),
        migrations.AlterField(
            model_name='course_faze',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faze', to='home.course', verbose_name='دوره مورد نظر'),
        ),
    ]
