# Generated by Django 4.2.2 on 2024-07-06 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_search_alter_course_faze_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_soft',
            field=models.BooleanField(default=False, help_text='در صورت زدن این تیک دوره در دسته نرم قرار میگیرد نمایش داده می شود', verbose_name='نرم بودن'),
        ),
    ]
