# Generated by Django 4.2.2 on 2024-07-07 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_course_is_soft'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='show_discount',
            field=models.IntegerField(null=True, verbose_name='تخفیف نمایشی دوره'),
        ),
    ]
