# Generated by Django 4.2.2 on 2024-07-09 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_course_show_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='related_items',
            field=models.ManyToManyField(related_name='related_to', to='home.course'),
        ),
    ]
