# Generated by Django 4.2.2 on 2024-07-10 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_course_related_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='fake_student',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='تعداد دانش اموزان'),
        ),
        migrations.AddField(
            model_name='course',
            name='is_fake_student',
            field=models.BooleanField(default=False, help_text='در صورت زدن این تیک تعداد دانش اموزان را به صورت فیک نمایش می دهد نمایش داده می شود', verbose_name='تیک دانش اموز فیک'),
        ),
    ]
