# Generated by Django 4.2.2 on 2024-07-21 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_course_fake_student_course_is_fake_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='fake_id',
            field=models.IntegerField(null=True, verbose_name='ترتیب نمایش اخرین دوره ها'),
        ),
        migrations.CreateModel(
            name='FazeFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225, verbose_name='نام فایل')),
                ('link', models.CharField(max_length=550, verbose_name='لینک فایل مورد نظر')),
                ('faze', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.course_faze', verbose_name='فاز')),
            ],
        ),
    ]
