# Generated by Django 4.2.2 on 2024-07-22 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_course_fake_id_fazefiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='unable_buy',
            field=models.BooleanField(default=False, help_text='در صورت زدن این تیک دوره غیر قابل خرید می شود', verbose_name='غیر قابل خرید'),
        ),
    ]
