# Generated by Django 4.2.2 on 2023-08-06 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cart_faze'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart_faze',
            old_name='course',
            new_name='faze',
        ),
    ]
