# Generated by Django 4.2.2 on 2023-11-24 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MembersDietail', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='our_member',
            options={'verbose_name': 'عضو ها', 'verbose_name_plural': 'عضو های مجموعه'},
        ),
        migrations.CreateModel(
            name='Member_Cantact_Way',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_way', models.CharField(max_length=150, verbose_name='نام راه ارتباطی')),
                ('way', models.CharField(max_length=400, verbose_name=' راه ارتباطی')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='عضو')),
            ],
            options={
                'verbose_name': 'راه ارتباطی',
                'verbose_name_plural': 'راه های ارتباطی با اعضا',
            },
        ),
    ]
